language: php
php:
  - 7.1
  - 7.0
matrix:
  fast_finish: true
  allow_failures:
    - php: "7.2"
  include:
    - php: "7.1"
    - php: "7.2"
    - php: "7.1"
      env: DRUPAL_CORE=~8.5
    - php: "7.1"
      env: DRUPAL_CORE=8.6.x-dev
before_install:
  - phpenv config-rm xdebug.ini
  # Add the oauth token to prevent GitHub timeouts.
  - git config --global github.accesstoken $GITHUB_OAUTH_TOKEN
  - composer global require "hirak/prestissimo:^0.3"
before_script:
  - composer --version
  - if [[ "$DRUPAL_CORE" != none ]]; then composer require drupal/core:$DRUPAL_CORE; fi
install:
  - composer install
script:
  - scripts/demo-install.php install
